name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '21.0.2'

    - name: Grant execute permission for gradlew
      if: runner.os == 'Linux' # Chỉ chạy trên Linux
      run: chmod +x gradlew

    - name: Build and test engine module
      run: ./gradlew build
