# permissions for end users to view databaseservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: databaseserver-viewer-role
rules:
- apiGroups:
  - datorum.beandev.io
  resources:
  - databaseservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - datorum.beandev.io
  resources:
  - databaseservers/status
  verbs:
  - get
