---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - datorum.beandev.io
  resources:
  - databaseservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - datorum.beandev.io
  resources:
  - databaseservers/finalizers
  verbs:
  - update
- apiGroups:
  - datorum.beandev.io
  resources:
  - databaseservers/status
  verbs:
  - get
  - patch
  - update
